/**
 * Color Utilities
 * Handles color name to hex conversion and color validation
 */

export const getColorHex = colorName => {
  if (!colorName) return '#ccc';

  const colorMap = {
    red: '#ff0000',
    blue: '#0000ff',
    green: '#00ff00',
    yellow: '#ffff00',
    black: '#000000',
    white: '#ffffff',
    gray: '#808080',
    grey: '#808080',
    brown: '#a52a2a',
    orange: '#ffa500',
    purple: '#800080',
    pink: '#ffc0cb',
    navy: '#000080',
    maroon: '#800000',
    olive: '#808000',
    lime: '#00ff00',
    aqua: '#00ffff',
    teal: '#008080',
    silver: '#c0c0c0',
    gold: '#ffd700',
    indigo: '#4b0082',
    violet: '#ee82ee',
    coral: '#ff7f50',
    turquoise: '#40e0d0',
    beige: '#f5f5dc',
    ivory: '#fffff0',
    lavender: '#e6e6fa',
    plum: '#dda0dd',
    salmon: '#fa8072',
    tan: '#d2b48c',
    wheat: '#f5deb3',
    azure: '#f0ffff',
    bisque: '#ffe4c4',
    blanchedalmond: '#ffebcd',
    burlywood: '#deb887',
    cadetblue: '#5f9ea0',
    chartreuse: '#7fff00',
    chocolate: '#d2691e',
    cornflowerblue: '#6495ed',
    cornsilk: '#fff8dc',
    crimson: '#dc143c',
    cyan: '#00ffff',
    darkblue: '#00008b',
    darkcyan: '#008b8b',
    darkgoldenrod: '#b8860b',
    darkgray: '#a9a9a9',
    darkgreen: '#006400',
    darkkhaki: '#bdb76b',
    darkmagenta: '#8b008b',
    darkolivegreen: '#556b2f',
    darkorange: '#ff8c00',
    darkorchid: '#9932cc',
    darkred: '#8b0000',
    darksalmon: '#e9967a',
    darkseagreen: '#8fbc8f',
    darkslateblue: '#483d8b',
    darkslategray: '#2f4f4f',
    darkturquoise: '#00ced1',
    darkviolet: '#9400d3',
    deeppink: '#ff1493',
    deepskyblue: '#00bfff',
    dimgray: '#696969',
    dodgerblue: '#1e90ff',
    firebrick: '#b22222',
    floralwhite: '#fffaf0',
    forestgreen: '#228b22',
    fuchsia: '#ff00ff',
    gainsboro: '#dcdcdc',
    ghostwhite: '#f8f8ff',
    goldenrod: '#daa520',
    greenyellow: '#adff2f',
    honeydew: '#f0fff0',
    hotpink: '#ff69b4',
    indianred: '#cd5c5c',
    khaki: '#f0e68c',
    lightblue: '#add8e6',
    lightcoral: '#f08080',
    lightcyan: '#e0ffff',
    lightgoldenrodyellow: '#fafad2',
    lightgreen: '#90ee90',
    lightgray: '#d3d3d3',
    lightpink: '#ffb6c1',
    lightsalmon: '#ffa07a',
    lightseagreen: '#20b2aa',
    lightskyblue: '#87cefa',
    lightslategray: '#778899',
    lightsteelblue: '#b0c4de',
    lightyellow: '#ffffe0',
    limegreen: '#32cd32',
    linen: '#faf0e6',
    magenta: '#ff00ff',
    mediumaquamarine: '#66cdaa',
    mediumblue: '#0000cd',
    mediumorchid: '#ba55d3',
    mediumpurple: '#9370db',
    mediumseagreen: '#3cb371',
    mediumslateblue: '#7b68ee',
    mediumspringgreen: '#00fa9a',
    mediumturquoise: '#48d1cc',
    mediumvioletred: '#c71585',
    midnightblue: '#191970',
    mintcream: '#f5fffa',
    mistyrose: '#ffe4e1',
    moccasin: '#ffe4b5',
    navajowhite: '#ffdead',
    oldlace: '#fdf5e6',
    olivedrab: '#6b8e23',
    orangered: '#ff4500',
    orchid: '#da70d6',
    palegoldenrod: '#eee8aa',
    palegreen: '#98fb98',
    paleturquoise: '#afeeee',
    palevioletred: '#db7093',
    papayawhip: '#ffefd5',
    peachpuff: '#ffdab9',
    peru: '#cd853f',
    powderblue: '#b0e0e6',
    rosybrown: '#bc8f8f',
    royalblue: '#4169e1',
    saddlebrown: '#8b4513',
    sandybrown: '#f4a460',
    seagreen: '#2e8b57',
    seashell: '#fff5ee',
    sienna: '#a0522d',
    skyblue: '#87ceeb',
    slateblue: '#6a5acd',
    slategray: '#708090',
    snow: '#fffafa',
    springgreen: '#00ff7f',
    steelblue: '#4682b4',
    thistle: '#d8bfd8',
    tomato: '#ff6347',
    transparent: 'transparent',
    violet: '#ee82ee',
    whitesmoke: '#f5f5f5',
    yellowgreen: '#9acd32',
  };

  const normalizedColor = colorName.toString().toLowerCase().trim();
  return colorMap[normalizedColor] || '#ccc';
};

/**
 * Get color name from hex value
 * @param {string} hexColor - Hex color value
 * @returns {string} - Color name
 */
export const getColorName = hexColor => {
  if (!hexColor) return 'Default';

  const colorMap = {
    '#ff0000': 'Red',
    '#0000ff': 'Blue',
    '#00ff00': 'Green',
    '#ffff00': 'Yellow',
    '#000000': 'Black',
    '#ffffff': 'White',
    '#808080': 'Gray',
    '#a52a2a': 'Brown',
    '#ffa500': 'Orange',
    '#800080': 'Purple',
    '#ffc0cb': 'Pink',
    '#000080': 'Navy',
    '#800000': 'Maroon',
    '#808000': 'Olive',
    '#00ffff': 'Aqua',
    '#008080': 'Teal',
    '#c0c0c0': 'Silver',
    '#ffd700': 'Gold',
    '#4b0082': 'Indigo',
    '#ee82ee': 'Violet',
    '#ff7f50': 'Coral',
    '#40e0d0': 'Turquoise',
    '#f5f5dc': 'Beige',
    '#fffff0': 'Ivory',
    '#e6e6fa': 'Lavender',
    '#dda0dd': 'Plum',
    '#fa8072': 'Salmon',
    '#d2b48c': 'Tan',
    '#f5deb3': 'Wheat',
    '#f0ffff': 'Azure',
    '#ffe4c4': 'Bisque',
    '#ffebcd': 'Blanched Almond',
    '#deb887': 'Burlywood',
    '#5f9ea0': 'Cadet Blue',
    '#7fff00': 'Chartreuse',
    '#d2691e': 'Chocolate',
    '#6495ed': 'Cornflower Blue',
    '#fff8dc': 'Cornsilk',
    '#dc143c': 'Crimson',
    '#00008b': 'Dark Blue',
    '#008b8b': 'Dark Cyan',
    '#b8860b': 'Dark Goldenrod',
    '#a9a9a9': 'Dark Gray',
    '#006400': 'Dark Green',
    '#bdb76b': 'Dark Khaki',
    '#8b008b': 'Dark Magenta',
    '#556b2f': 'Dark Olive Green',
    '#ff8c00': 'Dark Orange',
    '#9932cc': 'Dark Orchid',
    '#8b0000': 'Dark Red',
    '#e9967a': 'Dark Salmon',
    '#8fbc8f': 'Dark Sea Green',
    '#483d8b': 'Dark Slate Blue',
    '#2f4f4f': 'Dark Slate Gray',
    '#00ced1': 'Dark Turquoise',
    '#9400d3': 'Dark Violet',
    '#ff1493': 'Deep Pink',
    '#00bfff': 'Deep Sky Blue',
    '#696969': 'Dim Gray',
    '#1e90ff': 'Dodger Blue',
    '#b22222': 'Firebrick',
    '#fffaf0': 'Floral White',
    '#228b22': 'Forest Green',
    '#ff00ff': 'Fuchsia',
    '#dcdcdc': 'Gainsboro',
    '#f8f8ff': 'Ghost White',
    '#daa520': 'Goldenrod',
    '#adff2f': 'Green Yellow',
    '#f0fff0': 'Honeydew',
    '#ff69b4': 'Hot Pink',
    '#cd5c5c': 'Indian Red',
    '#f0e68c': 'Khaki',
    '#add8e6': 'Light Blue',
    '#f08080': 'Light Coral',
    '#e0ffff': 'Light Cyan',
    '#fafad2': 'Light Goldenrod Yellow',
    '#90ee90': 'Light Green',
    '#d3d3d3': 'Light Gray',
    '#ffb6c1': 'Light Pink',
    '#ffa07a': 'Light Salmon',
    '#20b2aa': 'Light Sea Green',
    '#87cefa': 'Light Sky Blue',
    '#778899': 'Light Slate Gray',
    '#b0c4de': 'Light Steel Blue',
    '#ffffe0': 'Light Yellow',
    '#32cd32': 'Lime Green',
    '#faf0e6': 'Linen',
    '#66cdaa': 'Medium Aquamarine',
    '#0000cd': 'Medium Blue',
    '#ba55d3': 'Medium Orchid',
    '#9370db': 'Medium Purple',
    '#3cb371': 'Medium Sea Green',
    '#7b68ee': 'Medium Slate Blue',
    '#00fa9a': 'Medium Spring Green',
    '#48d1cc': 'Medium Turquoise',
    '#c71585': 'Medium Violet Red',
    '#191970': 'Midnight Blue',
    '#f5fffa': 'Mint Cream',
    '#ffe4e1': 'Misty Rose',
    '#ffe4b5': 'Moccasin',
    '#ffdead': 'Navajo White',
    '#fdf5e6': 'Old Lace',
    '#6b8e23': 'Olive Drab',
    '#ff4500': 'Orange Red',
    '#da70d6': 'Orchid',
    '#eee8aa': 'Pale Goldenrod',
    '#98fb98': 'Pale Green',
    '#afeeee': 'Pale Turquoise',
    '#db7093': 'Pale Violet Red',
    '#ffefd5': 'Papaya Whip',
    '#ffdab9': 'Peach Puff',
    '#cd853f': 'Peru',
    '#b0e0e6': 'Powder Blue',
    '#bc8f8f': 'Rosy Brown',
    '#4169e1': 'Royal Blue',
    '#8b4513': 'Saddle Brown',
    '#f4a460': 'Sandy Brown',
    '#2e8b57': 'Sea Green',
    '#fff5ee': 'Sea Shell',
    '#a0522d': 'Sienna',
    '#87ceeb': 'Sky Blue',
    '#6a5acd': 'Slate Blue',
    '#708090': 'Slate Gray',
    '#fffafa': 'Snow',
    '#00ff7f': 'Spring Green',
    '#4682b4': 'Steel Blue',
    '#d8bfd8': 'Thistle',
    '#ff6347': 'Tomato',
    '#9acd32': 'Yellow Green',
  };

  const normalizedHex = hexColor.toLowerCase();
  return colorMap[normalizedHex] || 'Custom';
};

/**
 * Validate if a color is valid
 * @param {string} color - Color value (hex or name)
 * @returns {boolean} - True if valid color
 */
export const isValidColor = color => {
  if (!color) return false;

  // Check if it's a valid hex color
  const hexRegex = /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/;
  if (hexRegex.test(color)) return true;

  // Check if it's a valid color name
  const colorNames = [
    'red',
    'blue',
    'green',
    'yellow',
    'black',
    'white',
    'gray',
    'grey',
    'brown',
    'orange',
    'purple',
    'pink',
    'navy',
    'maroon',
    'olive',
    'lime',
    'aqua',
    'teal',
    'silver',
    'gold',
    'indigo',
    'violet',
    'coral',
    'turquoise',
    'beige',
    'ivory',
    'lavender',
    'plum',
    'salmon',
    'tan',
    'wheat',
    'azure',
    'bisque',
    'blanchedalmond',
    'burlywood',
    'cadetblue',
    'chartreuse',
    'chocolate',
    'cornflowerblue',
    'cornsilk',
    'crimson',
    'cyan',
    'darkblue',
    'darkcyan',
    'darkgoldenrod',
    'darkgray',
    'darkgreen',
    'darkkhaki',
    'darkmagenta',
    'darkolivegreen',
    'darkorange',
    'darkorchid',
    'darkred',
    'darksalmon',
    'darkseagreen',
    'darkslateblue',
    'darkslategray',
    'darkturquoise',
    'darkviolet',
    'deeppink',
    'deepskyblue',
    'dimgray',
    'dodgerblue',
    'firebrick',
    'floralwhite',
    'forestgreen',
    'fuchsia',
    'gainsboro',
    'ghostwhite',
    'goldenrod',
    'greenyellow',
    'honeydew',
    'hotpink',
    'indianred',
    'khaki',
    'lightblue',
    'lightcoral',
    'lightcyan',
    'lightgoldenrodyellow',
    'lightgreen',
    'lightgray',
    'lightpink',
    'lightsalmon',
    'lightseagreen',
    'lightskyblue',
    'lightslategray',
    'lightsteelblue',
    'lightyellow',
    'limegreen',
    'linen',
    'magenta',
    'mediumaquamarine',
    'mediumblue',
    'mediumorchid',
    'mediumpurple',
    'mediumseagreen',
    'mediumslateblue',
    'mediumspringgreen',
    'mediumturquoise',
    'mediumvioletred',
    'midnightblue',
    'mintcream',
    'mistyrose',
    'moccasin',
    'navajowhite',
    'oldlace',
    'olivedrab',
    'orangered',
    'orchid',
    'palegoldenrod',
    'palegreen',
    'paleturquoise',
    'palevioletred',
    'papayawhip',
    'peachpuff',
    'peru',
    'powderblue',
    'rosybrown',
    'royalblue',
    'saddlebrown',
    'sandybrown',
    'seagreen',
    'seashell',
    'sienna',
    'skyblue',
    'slateblue',
    'slategray',
    'snow',
    'springgreen',
    'steelblue',
    'thistle',
    'tomato',
    'transparent',
    'violet',
    'whitesmoke',
    'yellowgreen',
  ];

  return colorNames.includes(color.toLowerCase());
};

/**
 * Get contrasting text color for background
 * @param {string} backgroundColor - Background color (hex)
 * @returns {string} - Text color (black or white)
 */
export const getContrastColor = backgroundColor => {
  if (!backgroundColor) return '#000000';

  // Convert hex to RGB
  const hex = backgroundColor.replace('#', '');
  const r = parseInt(hex.substr(0, 2), 16);
  const g = parseInt(hex.substr(2, 2), 16);
  const b = parseInt(hex.substr(4, 2), 16);

  // Calculate luminance
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;

  return luminance > 0.5 ? '#000000' : '#ffffff';
};

export default {
  getColorHex,
  getColorName,
  isValidColor,
  getContrastColor,
};
